name: flutter_encrypt_plus
description: Encrypt and Decrypt strings in flutter with pure Dart code.
version: 0.0.1
homepage: https://github.com/swarajkumarsingh/flutter_encrypt_plus

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
